version: "3.3"

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prova
      - MONGO_INITDB_ROOT_PASSWORD=SECRET
  backend:
    build: .
    ports:
      - 5000:5000
    volumes:
    - ./:/backend
    - /backend/node_modules
    environment:
      - MONGODB_URI=mongodb://prova:SECRET@mongodb:27017
      - CORS_ORIGINS=http://localhost:3000
      - COOKIE_KEY=any_long_and_random_string
      - OPENAI_SECRET_KEY=YOUR_OPENAI_SECRET_KEY
      - OPENAI_ENDPOINT=YOUR_OPENAI_ENDPOINT
      - ISSUER_BASE_URL=... #TODO: replace with your auth0 issuer url
      - AUDIENCE=... #TODO: replace with your auth0 audience example: https://api.yourdomain.com
      - TEST_MODE=true
      - S3_BUCKET=polyglot-uploads-dev
      - S3_REGION=eu-north-1
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      
      
    command: npm run dev
